name: AiShell
description: "Using command line on html"
dependencies:
  browser: ">=0.9.0 <0.10.0"
  jquery_for_pub: ">=1.0.0 <2.0.0"
  bootstrap: ">=3.3.0+4 <4.0.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"